/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

/**
 *
 * @author HP
 */
public class PanelTutorial extends javax.swing.JPanel {

    /**
     * Creates new form panelTutorial
     */
    public PanelTutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSiguiente = new javax.swing.JButton();
        backgorund = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btCiner.png"))); // NOI18N
        add(btSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 150, 40));

        backgorund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tutorial.png"))); // NOI18N
        add(backgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgorund;
    private javax.swing.JButton btSiguiente;
    // End of variables declaration//GEN-END:variables
}
