/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import GUI.PantallaJuego;

/**
 *
 * @author HP
 */
public class PanelCine extends javax.swing.JPanel {

    /**
     * Creates new form panelCine
     */
    public PanelCine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btSiguiente.png"))); // NOI18N
        siguiente.setPreferredSize(new java.awt.Dimension(150, 40));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cineInicio.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        PantallaJuego pj =  new PantallaJuego();
        pj.setVisible(false);
    }//GEN-LAST:event_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
