/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import static GUI2.Window.cargaP1;
import static GUI2.Window.cargaP2;
import GUIsoundManagement.Efectos;
import data.Inventario;
import data.ItemPickeable;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author jdoli
 */
public class PanelInventario extends javax.swing.JPanel{

    private DefaultListModel modelo;
    private static ArrayList<ItemPickeable> inv = new ArrayList<>();
    
    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
        muestraInfo();
        //muestraClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescrip = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescrip.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        lblDescrip.setText("jLabel1");
        add(lblDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 50));

        jScrollPane1.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N

        lstItems.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        lstItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstItems);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 250, 150));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuVolver.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 150, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuVolver.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackInventario.png"))); // NOI18N
        fondo.setText("jLabel1");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int posicion = lstItems.getSelectedIndex();
        lstItems.remove(posicion);
        
        muestraInfo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Efectos e1 = new Efectos();

        e1.playClickCerrar();
        cargaRooms();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstItemsMouseClicked

    }//GEN-LAST:event_lstItemsMouseClicked

    
    public void cargaPantallaInicio()
    {
        PanelInicio pcp = new PanelInicio();
        pcp.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pcp.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pcp);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();

    }
    
    public void muestraInfo()
    {
        String registro = "";

        modelo = new DefaultListModel();
        for (ItemPickeable item: inv)
        {
            registro = item.getNombre();
            modelo.add(0, registro);
        }
        lstItems.setModel(modelo);
    }
    
    /*public void muestraClick()
    {

        lblDescrip.setText(inv.get(muestraDato()).getDescripcion());
        
    }*/
    
    public ArrayList<ItemPickeable> getInv() {
        return inv;
    }

    public static void setInv(ArrayList<ItemPickeable> inv) {
        PanelInventario.inv = inv;
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JList<String> lstItems;
    // End of variables declaration//GEN-END:variables

    /*public int muestraDato()
    {
        int conta = 0;
        for (ItemPickeable item: inv)
        {
            if ()
            {
                
            }
        }
        return conta;
    }*/
    
    public void cargaRooms()
    {
        cargaP1().setVisible(true);
        cargaP2().setVisible(true);
    }
    
}
