/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import GUIsoundManagement.Efectos;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PanelWin extends javax.swing.JPanel implements KeyListener{
    Icon img = new ImageIcon(getClass().getResource("/Images/sprites/" + 
            PanelCrearPartida.jugador.getGenero() + ".gif"));
    Efectos fx = new Efectos();
    
    int velocidad = 5;
    /**
     * Creates new form panelWin
     */
    public PanelWin() {
        Window.TEMA_CINE.playRio();
        Window.TEMA_JUEGO.stop();
        initComponents();
        addKeyListener(this);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        Profe = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l.setIcon(img);
        add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 50, 60));

        Profe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sprites/Daniel_Salazar.gif"))); // NOI18N
        add(Profe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mapas/FinalWin.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Profe;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {}

    @Override
    public void keyPressed(KeyEvent e) { 
        switch (e.getKeyCode()){
            case KeyEvent.VK_UP :
                if(l.getY() >= 48){
                    l.setLocation(l.getX(), l.getY() - velocidad);
                }else{
                    l.setLocation(l.getX(), l.getY() - 0);
                }
                break;
            
            case KeyEvent.VK_DOWN :
                if(l.getY() <= 480){
                    l.setLocation(l.getX(), l.getY() + velocidad);
                }else{
                    l.setLocation(l.getX(), l.getY() + 0);
                }
                break;
            
            case KeyEvent.VK_LEFT :
                if(l.getX() >= 169){
                    l.setLocation(l.getX() - velocidad, l.getY());
                }else{
                    l.setLocation(l.getX() - 0, l.getY());
                }
                break;
            
            case KeyEvent.VK_RIGHT :
                if(l.getX() <= 286){
                    l.setLocation(l.getX() + velocidad, l.getY());
                }else{
                    l.setLocation(l.getX() + 0, l.getY());
                }
                break;
                
            case KeyEvent.VK_SHIFT :
                velocidad = 10;
                break;

            case KeyEvent.VK_SPACE:
                if((l.getX() >= 252 && l.getX() <= 320) && (l.getY() >= 10 && l.getY() <= 76)){
                    fx.playItemEspecial();
                    int value = JOptionPane.showConfirmDialog(this, "¿Desea Pasar?" , 
                            "Punto de guardado", JOptionPane.YES_NO_OPTION);
                    if(value == JOptionPane.YES_OPTION){
                        Window.TEMA_JUEGO.playFinalGanar();
                        PanelCrearPartida.partida.setPanelActual(this);   
                        cargarGanar();
                    }else{
                        Window.TEMA_JUEGO.playFinalPerder();
                        cargarPerder();
                    }
                }
                break;
            
            
            case KeyEvent.VK_ESCAPE:
                fx.playPausa();
                cargarPausa();
                break;
            
            
            case KeyEvent.VK_I:
                fx.playPausa();
                cargarInventario();
                break;
            
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        switch (e.getKeyCode()){
            case KeyEvent.VK_SHIFT :
                velocidad = 5;
                break;
        }
    }
    
    public void cargarPausa(){
        PanelMenuPausa pm = new PanelMenuPausa();
        pm.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pm.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pm);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
    
    public void cargarInventario(){
        PanelInventario pm = new PanelInventario();
        pm.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pm.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pm);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
    
    public void cargarPerder(){
        PanelPerder pj = new PanelPerder();
        pj.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pj.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pj);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
    
    public void cargarGanar(){
        PanelGanar pj = new PanelGanar();
        pj.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pj.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pj);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
}
