/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import GUIsoundManagement.Efectos;
import GUIsoundManagement.Pistas;
import java.io.Serializable;

/**
 *
 * @author HP
 */
public class PanelPerder extends javax.swing.JPanel implements Serializable{
    long tiempo = System.currentTimeMillis()/1000 - Window.time/1000;
    Pistas voces = new Pistas();
    /**
     * Creates new form panelPerder
     */
    public PanelPerder() {
        voces.playVoces();
        initComponents();
        PanelCrearPartida.jugador.setTiempo(tiempo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSiguiente = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btSiguiente.png"))); // NOI18N
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });
        add(btSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mapas/perder.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        voces.stop();
        Efectos fx = new Efectos();
        fx.playQuitarPausa();
        Window.TEMA_CINE.stop();
        Window.TEMA_JUEGO.stop();
        Window.TEMA_JUEGO.playMenuTheme();
        cargarScore();
    }//GEN-LAST:event_btSiguienteActionPerformed
    
    public void cargarScore(){
        PanelScore pj = new PanelScore();
        pj.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pj.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pj);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSiguiente;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
