/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import static GUI2.PanelIglesia.l;
import GUIsoundManagement.Efectos;
import data.Inventario;
import data.ItemPickeable;
import data.Jugador;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jdoli
 */
public class PanelInventario extends javax.swing.JPanel implements KeyListener{
    Icon emerald = new ImageIcon(getClass().getResource("/Images/objetos/emerald.png"));
    Icon ruby = new ImageIcon(getClass().getResource("/Images/objetos/ruby.png"));
    Icon topaz = new ImageIcon(getClass().getResource("/Images/objetos/topaz.png"));
    Icon sap = new ImageIcon(getClass().getResource("/Images/objetos/sap.png"));
    
    private DefaultTableModel modelo;
    private static ArrayList<ItemPickeable> inv = new ArrayList<>();
    
    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        inv = Jugador.inventario;
        Window.TEMA_JUEGO.stop();
        initComponents();
        muestraInfo();
        //muestraClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblInv = new javax.swing.JTable();
        volver = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInv.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        tblInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblInv);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 420, 190));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuVolver.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 150, 40));

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuMostrar.png"))); // NOI18N
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackInventario.png"))); // NOI18N
        fondo.setText("jLabel1");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        Efectos e2 = new Efectos();
        e2.playItem();

    }//GEN-LAST:event_mostrarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Efectos e1 = new Efectos();
         int value = JOptionPane.showConfirmDialog(this, "Volver al Juego",
            "Volver", JOptionPane.DEFAULT_OPTION);
        if(value == JOptionPane.OK_OPTION){
            Window.TEMA_JUEGO.playGamePlay();
            e1.playQuitarPausa();
            PanelIglesia.l.setLocation(PanelIglesia.guardaPosX(), PanelIglesia.guardaPosY());
            cargarVolver();
        }
    }//GEN-LAST:event_volverActionPerformed

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()){
            case KeyEvent.VK_I :
                cargarVolver();
                break;
        }
    }
    
    public void cargaPantallaInicio()
    {
        PanelInicio pcp = new PanelInicio();
        pcp.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pcp.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pcp);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();

    }
    

    
    public void muestraInfo()
    {
        /*for (int i = 0; i = tblInv.getColumnCount(); i++)
        {
            if (i == 0)
            {
                tblInv.set
            }
        }
        column = tblInv.getColumnCount();
        
        
        String[] titulo = {"", "", ""};
        String[] registro = new String[2];
        Icon[] icons = new Icon[1];

 
        modelo = new DefaultTableModel(null, titulo);
        for (ItemPickeable item: inv)
        {
            //icons[0] = item.getIm();
            registro[0] = item.getNombre();
            registro[1] = item.getDescripcion();
            //modelo.add
            modelo.addRow(registro);
        }
        tblInv.setModel(modelo);*/
    }
    
    /*public void muestraClick()
    {

        lblDescrip.setText(inv.get(muestraDato()).getDescripcion());
        
    }*/
    
    public ArrayList<ItemPickeable> getInv() {
        return inv;
    }

    public static void setInv(ArrayList<ItemPickeable> inv) {
        PanelInventario.inv = inv;
    }
    
     public void cargarVolver()
    {
        JPanel pcp = new JPanel();
        pcp = PanelCrearPartida.partida.getPanelActual();
        pcp.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pcp.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pcp);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mostrar;
    private javax.swing.JTable tblInv;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        }

    @Override
    public void keyReleased(KeyEvent e) {
        }

    /*public int muestraDato()
    {
        int conta = 0;
        for (ItemPickeable item: inv)
        {
            if ()
            {
                
            }
        }
        return conta;
    }*/
    
}
