/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import GUIsoundManagement.Efectos;
import data.Inventario;
import data.ItemPickeable;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author jdoli
 */
public class PanelInventario extends javax.swing.JPanel{
    Icon emerald = new ImageIcon(getClass().getResource("/Images/objetos/emerald.png"));
    Icon ruby = new ImageIcon(getClass().getResource("/Images/objetos/ruby.png"));
    Icon topaz = new ImageIcon(getClass().getResource("/Images/objetos/topaz.png"));
    Icon sap = new ImageIcon(getClass().getResource("/Images/objetos/sap.png"));
    
    private DefaultListModel modelo;
    private static ArrayList<ItemPickeable> inv = new ArrayList<>();
    
    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        Window.TEMA_JUEGO.stop();
        initComponents();
        muestraInfo();
        //muestraClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        volver = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, 50));

        jScrollPane1.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N

        lstItems.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        lstItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstItems);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 250, 150));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuVolver.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 150, 40));

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btMenuMostrar.png"))); // NOI18N
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackInventario.png"))); // NOI18N
        fondo.setText("jLabel1");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        Efectos e2 = new Efectos();
        e2.playItem();
        int posicion = lstItems.getSelectedIndex();
        lstItems.remove(posicion);
        
        muestraInfo();
    }//GEN-LAST:event_mostrarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Efectos e1 = new Efectos();
         int value = JOptionPane.showConfirmDialog(this, "Volver al Juego",
            "Volver", JOptionPane.DEFAULT_OPTION);
        if(value == JOptionPane.OK_OPTION){
            Window.TEMA_JUEGO.playGamePlay();
            e1.playQuitarPausa();
            cargarVolver();
        }
    }//GEN-LAST:event_volverActionPerformed

    private void lstItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstItemsMouseClicked

    }//GEN-LAST:event_lstItemsMouseClicked

    
    public void cargaPantallaInicio()
    {
        PanelInicio pcp = new PanelInicio();
        pcp.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pcp.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pcp);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();

    }
    
    public void muestraInfo()
    {
        String registro = "";

        modelo = new DefaultListModel();
        for (ItemPickeable item: inv)
        {
            registro = item.getNombre();
            modelo.add(0, registro);
        }
        lstItems.setModel(modelo);
    }
    
    /*public void muestraClick()
    {

        lblDescrip.setText(inv.get(muestraDato()).getDescripcion());
        
    }*/
    
    public ArrayList<ItemPickeable> getInv() {
        return inv;
    }

    public static void setInv(ArrayList<ItemPickeable> inv) {
        PanelInventario.inv = inv;
    }
    
     public void cargarVolver()
    {
        JPanel pcp = new JPanel();
        pcp = PanelCrearPartida.partida.getPanelActual();
        pcp.setSize(Window.getJpanel().getWidth(), Window.getJpanel().getHeight());
        pcp.setLocation(0,0);
        
        Window.getJpanel().removeAll();
        Window.getJpanel().add(pcp);
        Window.getJpanel().revalidate();
        Window.getJpanel().repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> lstItems;
    private javax.swing.JButton mostrar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    /*public int muestraDato()
    {
        int conta = 0;
        for (ItemPickeable item: inv)
        {
            if ()
            {
                
            }
        }
        return conta;
    }*/
    
}
