/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI2;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author HP
 */
public class PanelJuego extends javax.swing.JPanel implements KeyListener{

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        
        addKeyListener(this);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sprites/ProtaFemFront.gif"))); // NOI18N
        add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iglesia.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()){
            case KeyEvent.VK_UP :{
                l.setLocation(l.getX(), l.getY() - 5);
                break;
            }
            case KeyEvent.VK_DOWN :{
                l.setLocation(l.getX(), l.getY() + 5);
                break;
            }
            case KeyEvent.VK_LEFT :{
                l.setLocation(l.getX() - 5, l.getY());
                break;
            }
            case KeyEvent.VK_RIGHT :{
                l.setLocation(l.getX() + 5, l.getY());
                break;
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
