/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rooms;

import GUI2.Window;
import data.Teclado;
import static data.Teclado.cargaNext;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author jdoli
 */
public class PanelJuegoV2 extends Teclado{
    
@Override
public void eventos(KeyEvent e)
        {
           if (e.getKeyCode() == KeyEvent.VK_SPACE)
           {
               //Puerta
                if((x >= 275 && x <= 325) && (y >= 185 && y <= 215)){
                    JOptionPane.showMessageDialog(this, "Ganastes");
                    Window.cargaP1().setVisible(false);
                    Window.cargaP2().setVisible(true);
                    velX = 0;
                    velY = 0;
                }
                //Punto de guardado
                if((x >= 375 && x <= 425) && (y >= 285 && y <= 315)){
                    
                    JOptionPane.showMessageDialog(this, "El juego se ha guardado correctamente");
                    velX = 0;
                    velY = 0;
                }
           }
        }

    /**
     * Creates new form PanelJuegoV2
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
