/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.CrearPartida.estado;
import GUIsoundManagement.Efectos;
import data.Jugador;
import data.Mapa;
import data.Partida;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author jdoli
 */
public class CargarPartida extends VentanaSecundaria {

    private String fichero = ".\\src\\savedFiles\\Saved.obj";
    /**
     * Creates new form CargarPartida
     */
    public CargarPartida() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPartidas = new Lista();
        jLabel1 = new javax.swing.JLabel();
        buttonCargar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPartidas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        listaPartidas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPartidasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPartidas);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cargar Partida");

        buttonCargar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        buttonCargar.setText("Cargar");
        buttonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarActionPerformed(evt);
            }
        });

        buttonSalir.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalir)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarActionPerformed
        int s = listaPartidas.getSelectedIndex();
        ArrayList<Partida> partidasRecargadas = new ArrayList<>();
        this.cargarPartida((Boton) buttonCargar, partidasRecargadas.get(s));
    }//GEN-LAST:event_buttonCargarActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        //botón salir
        Efectos e1 = new Efectos();
        e1.playClickCerrar();
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea salir sin Guardar?", "Aviso", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void listaPartidasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPartidasValueChanged

    }//GEN-LAST:event_listaPartidasValueChanged

    private Partida listaPartidaActionPerformed(java.awt.event.ActionEvent evt) {
        Partida seleccionada = new Partida();
        Efectos e1 = new Efectos();
        e1.playClickPositivo();
        return seleccionada;
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarPartida().setVisible(true);
            }
        });
        
    }
    
    public PantallaJuego seleccionarPartida(){
        return null;
    }
    
    public Partida cargarPartida(Boton a, Partida carga){
        Partida cargaPartida = new Partida();
        Jugador cargaJugador = new Jugador(null, null, null, null);
        Mapa carganuevoMapa = new Mapa(null,null,null);  
        long tiempoTotal = System.currentTimeMillis();

        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                /*cargaJugador.setNombre(b.getText());
                cargaJugador.setGenero(c.getSelection().toString());
                cargaPartida.setTiempo((System.currentTimeMillis()-tiempoTotal)/1000);
                cargaPartida.setJugadorActual(nuevoJugador);*/
                PantallaJuego cargaPantalla = new PantallaJuego();
                estado = true;
                System.out.println(estado);
                dispose();
            }
        };
        a.addActionListener(action);
        return cargaPartida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCargar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPartidas;
    // End of variables declaration//GEN-END:variables

}
